--
-- FT_EMAIL  (Package) 
--
CREATE OR REPLACE PACKAGE FT_EMAIL AS 

  PROCEDURE PROCESS_EMAILS;
  
  FUNCTION FT_ERROR_LOG_MSG RETURN CLOB;
  PROCEDURE FT_ERROR_LOG_FLAG(EMAILBATCHNO_IN INTEGER);

END FT_EMAIL;
/
