CREATE OR REPLACE PACKAGE FT_PK_SESSION_UTILS AS

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number

  FUNCTION GET_FT_LOGONNO RETURN LOGONS.LOGONNO%TYPE;
  FUNCTION GET_SID RETURN INTEGER;

END FT_PK_SESSION_UTILS;
/
