create or replace PACKAGE FT_PK_TRANS_COSTS AS

 	cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number

	FUNCTION  CURRENTVERSION RETURN VARCHAR2;

	PROCEDURE TRANSFERADDCHGSAPP_BYRTHNO(RTHNO_IN RECORD_NUMBERS);
	PROCEDURE TRANSFERADDCHGSAPP_BYEXPCHA(EXCCHAREC_IN RECORD_NUMBERS);
	PROCEDURE TRANSFERADDCHGSAPP_BYDLVORDNO(DLVORDNO_IN RECORD_NUMBERS);
	PROCEDURE TRANSFERADDCHGSAPP_BYDLV_DPR(DLVORDNO_IN RECORD_NUMBERS);

END FT_PK_TRANS_COSTS;
