CREATE OR REPLACE PACKAGE FT_PK_STRING_UTILS AS

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number

  TYPE TYPE_STRING_TOKENS IS TABLE OF VARCHAR2(30) INDEX BY VARCHAR2(30);

  PROCEDURE STRIPOUTCHAR(SRCSTR_INOUT IN OUT VARCHAR2, STRIPCHAR_IN IN VARCHAR2);
  PROCEDURE REPLACETOKENS(SRCSTR_INOUT IN OUT VARCHAR2, TOKEN_LIST IN TYPE_STRING_TOKENS);

END FT_PK_STRING_UTILS;
/
