CREATE OR REPLACE PACKAGE FT_PK_GETSALES AS 

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number
  
  FUNCTION CURRENTVERSION RETURN VARCHAR2;

  PROCEDURE GETSALES;
  PROCEDURE GETSALES(DPRRECNO_IN DELPRICE.DPRRECNO%TYPE);

END FT_PK_GETSALES;
/
