CREATE OR REPLACE PACKAGE FT_PK_GOODS_COSTS AS 

  cSpecVersionControlNo VARCHAR2(12) := '1.0.1';
  
  FUNCTION CURRENTVERSION(IN_BODYORSPEC IN INTEGER ) RETURN VARCHAR2;

  PROCEDURE CALCULATEGOODSCOST;
  PROCEDURE CALCULATEGOODSCOST(LITITENO_IN LOTITE.LITITENO%TYPE);

END FT_PK_GOODS_COSTS;
/
