CREATE OR REPLACE PACKAGE FT_PK_DB_UTILS AS

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number
  
  FUNCTION CURRENTVERSION RETURN VARCHAR2;

  FUNCTION TABLE_EXISTS(TABLE_NAME_IN VARCHAR2) RETURN BOOLEAN;

END FT_PK_DB_UTILS;
/
