CREATE OR REPLACE PACKAGE FT_PK_SESSION_UTILS AS

  cSpecVersionControlNo VARCHAR2(12) := '1.0.1';
  
  FUNCTION CURRENTVERSION(IN_BODYORSPEC IN INTEGER ) RETURN VARCHAR2;

  FUNCTION GET_FT_LOGONNO RETURN LOGONS.LOGONNO%TYPE;
  FUNCTION GET_SID RETURN INTEGER;
  
  FUNCTION LIST_ACTIVE_SID RETURN RECORD_NUMBERS;

END FT_PK_SESSION_UTILS;
/
