CREATE OR REPLACE PACKAGE FT_PK_PROFITISELOTS AS

  cSpecVersionControlNo VARCHAR2(12) := '1.0.2';
  
  FUNCTION CURRENTVERSION(IN_BODYORSPEC IN INTEGER ) RETURN VARCHAR2;

  PROCEDURE LOTPROFITABILITY;
  PROCEDURE LOTPROFITABILITY(LITITENO_IN LOTITE.LITITENO%TYPE);

END FT_PK_PROFITISELOTS;
/
