CREATE OR REPLACE PACKAGE FT_PK_GOODS_COSTS AS 

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number
  
  FUNCTION CURRENTVERSION RETURN VARCHAR2;

  PROCEDURE CALCULATEGOODSCOST;
  PROCEDURE CALCULATEGOODSCOST(LITITENO_IN LOTITE.LITITENO%TYPE);

END FT_PK_GOODS_COSTS;
/
