--
-- FT_PK_WO_COSTS  (Package) 
--
CREATE OR REPLACE PACKAGE FT_PK_WO_COSTS AS 

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number
  FUNCTION CURRENTVERSION RETURN VARCHAR2;
  
  PROCEDURE RECALCULATEWOCOSTS(BULKLOTITENOLI_IN LOTITE.LITITENO%TYPE);
  PROCEDURE RECALCULATEWOCOSTS;

END FT_PK_WO_COSTS;
/
