CREATE OR REPLACE PACKAGE FT_PK_GETSALES AS 

  cSpecVersionControlNo VARCHAR2(12) := '1.0.1';
  
  FUNCTION CURRENTVERSION(IN_BODYORSPEC IN INTEGER ) RETURN VARCHAR2;

  PROCEDURE GETSALES;
  PROCEDURE GETSALES(DPRRECNO_IN DELPRICE.DPRRECNO%TYPE);

END FT_PK_GETSALES;
/
