CREATE OR REPLACE PACKAGE FT_PK_PROFITISELOTS AS

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number
  
  FUNCTION CURRENTVERSION RETURN VARCHAR2;

  PROCEDURE LOTPROFITABILITY;
  PROCEDURE LOTPROFITABILITY(LITITENO_IN LOTITE.LITITENO%TYPE);

END FT_PK_PROFITISELOTS;
/
