CREATE OR REPLACE PACKAGE FT_PK_EMAIL AS

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number
  
  FUNCTION CURRENTVERSION RETURN VARCHAR2;

  PROCEDURE PROCESS_EMAILS;

  FUNCTION FT_ERROR_LOG_MSG RETURN CLOB;
  PROCEDURE FT_ERROR_LOG_FLAG(EMAILBATCHNO_IN INTEGER);

END FT_PK_EMAIL;
/
