CREATE OR REPLACE PACKAGE FT_PK_SALES  AS

  --cVersionControlNo   VARCHAR2(12) := '1.0.0'; -- Current Version Number

  PROCEDURE DELPRICE_NETTVALUE(IN_DPRRECNO IN NUMBER );

  PROCEDURE DELPRICE_CALCVATFIGURES(IN_DPRRECNO IN NUMBER);

  PROCEDURE DELTOIST_UPDATEVALUES(IN_DPRRECNO IN NUMBER, VERIFYDELIVERY NUMBER);
  
  FUNCTION GET_LOT_SOLD_QTY(LITITENO_IN LOTITE.LITITENO%TYPE) RETURN FLOAT;

END FT_PK_SALES;
/
