--
-- FT_PK_WO_COSTS  (Package) 
--
CREATE OR REPLACE PACKAGE FT_PK_WO_COSTS AS 

  cSpecVersionControlNo VARCHAR2(12) := '1.0.1';
  FUNCTION CURRENTVERSION(IN_BODYORSPEC IN INTEGER ) RETURN VARCHAR2;
  
  PROCEDURE RECALCULATEWOCOSTS(BULKLOTITENOLI_IN LOTITE.LITITENO%TYPE);
  PROCEDURE RECALCULATEWOCOSTS;

END FT_PK_WO_COSTS;
/
