--
-- TO_BOOLEAN  (Function) 
--
CREATE OR REPLACE FUNCTION TO_BOOLEAN
  ( P_STRING VARCHAR2
  ) RETURN BOOLEAN
IS
BEGIN
  RETURN
    CASE UPPER(TRIM(P_STRING)) 
      WHEN 'TRUE' THEN TRUE
      WHEN 'FALSE' THEN FALSE
      ELSE NULL
      END;
END;
/
