--v1.0.1
CREATE OR REPLACE TRIGGER DGPAMENDMENTS 
AFTER INSERT ON AUTOCOSTS_PROCESS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  FT_PK_DGP.ENQUEUE_DGPDPRSTODO(:NEW.DPRRECNO);
EXCEPTION
  WHEN OTHERS THEN 
    FT_PK_ERRORS.LOG_AND_CONTINUE;
END;
/