CREATE OR REPLACE TRIGGER FT_TG_AUTOCOSTSTODO_PROCTIME
BEFORE UPDATE ON AUTOCOSTSTODO
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW   
DECLARE
  CVERSIONCONTROLNO   VARCHAR2(12) := '1.0.1'; -- Current Version Number
BEGIN
  BEGIN
    IF NVL(:OLD.PROCESSSTAT, -1) <>  NVL(:NEW.PROCESSSTAT, -1)
    OR NVL(:OLD.SESSIONNO, -1) <>  NVL(:NEW.SESSIONNO, -1)  THEN
      :NEW.PROCESSSTARTTIME     := SYSDATE;
    END IF;
  END ;
END;
