CREATE OR REPLACE VIEW FT_V_PERFMON ( PERFMON_BATCH_NO, 
PORSALOFF, FT_PERFMON_TYPENO, FT_PERFMON_DESC, TABLE_REF, SELECTIONCRITERIA, 
TABLE_REF_VALUE, NORECORDS, LITITENO, ELAPSED_TIME, 
ELAPSED_HOURS, ELAPSED_MINUTES, ELAPSED_SECONDS, START_DATE_TIME, 
END_DATE_TIME, LOGONNO, LOGONNAME, USERNAME, 
COMPUTERNAME, FORMNO, FORMNAME, FORMTIT
 ) AS SELECT FT_PERFMON.PERFMON_BATCH_NO,
	   PURORD.PORSALOFF,
	   FT_PERFMON_KEYS.FT_PERFMON_TYPENO,
	   TRIM(FT_PERFMON_KEYS.FT_PERFMON_DESC) AS FT_PERFMON_DESC,
	   TRIM(FT_PERFMON.SELECTIONCRITERIA) AS SELECTIONCRITERIA,
	   TRIM(FT_PERFMON_KEYS.TABLE_REF) AS TABLE_REF,
	   PURORD.PORNO AS TABLE_REF_VALUE,
	   FT_PERFMON.NORECORDS,
	   NULL AS LitIteNo,
	   to_char(to_date('00:00:00', 'HH24:MI:SS') + (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME),  'HH24:MI:SS') AS Elapsed_Time,
	   MOD(TRUNC( 24 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Hours,
	   MOD(TRUNC( 24 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Minutes,
	   MOD(TRUNC( 24 * 60 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Seconds,
	   FT_PERFMON.START_DATE_TIME,
	   FT_PERFMON.END_DATE_TIME,
	   LOGONS.LOGONNO,
	   LOGONS.LOGONNAME,
	   LOGONS.USERNAME,
	   USERSESSNOLOG.COMPUTERNAME,
	   FRMNAME.FORMNO,
	   FRMNAME.FORMNAME,
	   FRMNAME.FORMTIT
  FROM FT_PERFMON
  	   INNER JOIN FT_PERFMON_KEYS ON (FT_PERFMON.FT_PERFMON_TYPENO = FT_PERFMON_KEYS.FT_PERFMON_TYPENO)
	   INNER JOIN USERSESSNOLOG ON (FT_PERFMON.PERFMONUSER = USERSESSNOLOG.USLRECNO)
	   INNER JOIN LOGONS ON (USERSESSNOLOG.LOGONNO = LOGONS.LOGONNO)
	   INNER JOIN PURORD ON (FT_PERFMON.TABLE_REF_VALUE = PURORD.PORNO)
	   LEFT OUTER JOIN FRMNAME ON (FT_PERFMON.FormNumber = FRMNAME.FORMNO)
 WHERE FT_PERFMON.FT_PERFMON_TYPENO = 1
   /*AND EXISTS(SELECT SESSNO.USERSESSRECNO
   	   			FROM USERSESSNOLOG SESSNO
			   WHERE SESSNO.ISLOGIN = 1
			   GROUP BY SESSNO.USERSESSRECNO
			  HAVING MAX(SESSNO.USLRECNO) = USERSESSNOLOG.USLRECNO)*/

UNION ALL

SELECT FT_PERFMON.PERFMON_BATCH_NO,
	   PURORD.PORSALOFF,
	   FT_PERFMON_KEYS.FT_PERFMON_TYPENO,
	   TRIM(FT_PERFMON_KEYS.FT_PERFMON_DESC) AS FT_PERFMON_DESC,
	   TRIM(FT_PERFMON.SELECTIONCRITERIA) AS SELECTIONCRITERIA,
	   TRIM(FT_PERFMON_KEYS.TABLE_REF) AS TABLE_REF,
	   PURORD.PORNO AS TABLE_REF_VALUE,
	   FT_PERFMON.NORECORDS,
	   NULL AS LitIteNo,
	   to_char(to_date('00:00:00', 'HH24:MI:SS') + (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME),  'HH24:MI:SS') AS Elapsed_Time,
	   MOD(TRUNC( 24 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Hours,
	   MOD(TRUNC( 24 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Minutes,
	   MOD(TRUNC( 24 * 60 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Seconds,
	   FT_PERFMON.START_DATE_TIME,
	   FT_PERFMON.END_DATE_TIME,
	   LOGONS.LOGONNO,
	   LOGONS.LOGONNAME,
	   LOGONS.USERNAME,
	   USERSESSNOLOG.COMPUTERNAME,
	   FRMNAME.FORMNO,
	   FRMNAME.FORMNAME,
	   FRMNAME.FORMTIT
  FROM FT_PERFMON
  	   INNER JOIN FT_PERFMON_KEYS ON (FT_PERFMON.FT_PERFMON_TYPENO = FT_PERFMON_KEYS.FT_PERFMON_TYPENO)
	   INNER JOIN USERSESSNOLOG ON (FT_PERFMON.PERFMONUSER = USERSESSNOLOG.USLRECNO)
	   INNER JOIN LOGONS ON (USERSESSNOLOG.LOGONNO = LOGONS.LOGONNO)
	   INNER JOIN PURORD ON (FT_PERFMON.TABLE_REF_VALUE = PURORD.PORNO)
	   LEFT OUTER JOIN FRMNAME ON (FT_PERFMON.FormNumber = FRMNAME.FORMNO)
 WHERE FT_PERFMON.FT_PERFMON_TYPENO = 2
   /*AND EXISTS(SELECT SESSNO.USERSESSRECNO
   	   			FROM USERSESSNOLOG SESSNO
			   WHERE SESSNO.ISLOGIN = 1
			   GROUP BY SESSNO.USERSESSRECNO
			  HAVING MAX(SESSNO.USLRECNO) = USERSESSNOLOG.USLRECNO)*/

UNION ALL

SELECT FT_PERFMON.PERFMON_BATCH_NO,
	   PURORD.PORSALOFF,
	   FT_PERFMON_KEYS.FT_PERFMON_TYPENO,
	   TRIM(FT_PERFMON_KEYS.FT_PERFMON_DESC) AS FT_PERFMON_DESC,
	   TRIM(FT_PERFMON.SELECTIONCRITERIA) AS SELECTIONCRITERIA,
	   TRIM(FT_PERFMON_KEYS.TABLE_REF) AS TABLE_REF,
	   PURORD.PORNO AS TABLE_REF_VALUE,
	   FT_PERFMON.NORECORDS,
	   LOTITE.LITITENO AS LitIteNo,
	   to_char(to_date('00:00:00', 'HH24:MI:SS') + (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME),  'HH24:MI:SS') AS Elapsed_Time,
	   MOD(TRUNC( 24 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Hours,
	   MOD(TRUNC( 24 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Minutes,
	   MOD(TRUNC( 24 * 60 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Seconds,
	   FT_PERFMON.START_DATE_TIME,
	   FT_PERFMON.END_DATE_TIME,
	   LOGONS.LOGONNO,
	   LOGONS.LOGONNAME,
	   LOGONS.USERNAME,
	   USERSESSNOLOG.COMPUTERNAME,
	   FRMNAME.FORMNO,
	   FRMNAME.FORMNAME,
	   FRMNAME.FORMTIT
  FROM FT_PERFMON
  	   INNER JOIN FT_PERFMON_KEYS ON (FT_PERFMON.FT_PERFMON_TYPENO = FT_PERFMON_KEYS.FT_PERFMON_TYPENO)
	   INNER JOIN USERSESSNOLOG ON (FT_PERFMON.PERFMONUSER = USERSESSNOLOG.USLRECNO)
	   INNER JOIN LOGONS ON (USERSESSNOLOG.LOGONNO = LOGONS.LOGONNO)
	   INNER JOIN LOTITE ON (FT_PERFMON.TABLE_REF_VALUE = LOTITE.LITITENO)
	   INNER JOIN PURORD ON (LOTITE.LITPORREC = PURORD.PORRECNO)
	   LEFT OUTER JOIN FRMNAME ON (FT_PERFMON.FormNumber = FRMNAME.FORMNO)
 WHERE FT_PERFMON.FT_PERFMON_TYPENO = 3
   /*AND EXISTS(SELECT SESSNO.USERSESSRECNO
   	   			FROM USERSESSNOLOG SESSNO
			   WHERE SESSNO.ISLOGIN = 1
			   GROUP BY SESSNO.USERSESSRECNO
			  HAVING MAX(SESSNO.USLRECNO) = USERSESSNOLOG.USLRECNO)*/

UNION ALL

SELECT FT_PERFMON.PERFMON_BATCH_NO,
	   PURORD.PORSALOFF,
	   FT_PERFMON_KEYS.FT_PERFMON_TYPENO,
	   TRIM(FT_PERFMON_KEYS.FT_PERFMON_DESC) AS FT_PERFMON_DESC,
	   TRIM(FT_PERFMON.SELECTIONCRITERIA) AS SELECTIONCRITERIA,
	   TRIM(FT_PERFMON_KEYS.TABLE_REF) AS TABLE_REF,
	   PURORD.PORNO AS TABLE_REF_VALUE,
	   FT_PERFMON.NORECORDS,
	   LOTITE.LITITENO AS LitIteNo,
	   to_char(to_date('00:00:00', 'HH24:MI:SS') + (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME),  'HH24:MI:SS') AS Elapsed_Time,
	   MOD(TRUNC( 24 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Hours,
	   MOD(TRUNC( 24 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Minutes,
	   MOD(TRUNC( 24 * 60 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Seconds,
	   FT_PERFMON.START_DATE_TIME,
	   FT_PERFMON.END_DATE_TIME,
	   LOGONS.LOGONNO,
	   LOGONS.LOGONNAME,
	   LOGONS.USERNAME,
	   USERSESSNOLOG.COMPUTERNAME,
	   FRMNAME.FORMNO,
	   FRMNAME.FORMNAME,
	   FRMNAME.FORMTIT
  FROM FT_PERFMON
  	   INNER JOIN FT_PERFMON_KEYS ON (FT_PERFMON.FT_PERFMON_TYPENO = FT_PERFMON_KEYS.FT_PERFMON_TYPENO)
	   INNER JOIN USERSESSNOLOG ON (FT_PERFMON.PERFMONUSER = USERSESSNOLOG.USLRECNO)
	   INNER JOIN LOGONS ON (USERSESSNOLOG.LOGONNO = LOGONS.LOGONNO)
	   INNER JOIN LOTITE ON (FT_PERFMON.TABLE_REF_VALUE = LOTITE.LITITENO)
	   INNER JOIN PURORD ON (LOTITE.LITPORREC = PURORD.PORRECNO)
	   LEFT OUTER JOIN FRMNAME ON (FT_PERFMON.FormNumber = FRMNAME.FORMNO)
 WHERE FT_PERFMON.FT_PERFMON_TYPENO = 4
   /*AND EXISTS(SELECT SESSNO.USERSESSRECNO
   	   			FROM USERSESSNOLOG SESSNO
			   WHERE SESSNO.ISLOGIN = 1
			   GROUP BY SESSNO.USERSESSRECNO
			  HAVING MAX(SESSNO.USLRECNO) = USERSESSNOLOG.USLRECNO)*/

UNION ALL

SELECT FT_PERFMON.PERFMON_BATCH_NO,
	   PURORD.PORSALOFF,
	   FT_PERFMON_KEYS.FT_PERFMON_TYPENO,
	   TRIM(FT_PERFMON_KEYS.FT_PERFMON_DESC) AS FT_PERFMON_DESC,
	   TRIM(FT_PERFMON.SELECTIONCRITERIA) AS SELECTIONCRITERIA,
	   TRIM(FT_PERFMON_KEYS.TABLE_REF) AS TABLE_REF,
	   PURORD.PORNO AS TABLE_REF_VALUE,
	   FT_PERFMON.NORECORDS,
	   NULL AS LitIteNo,
	   to_char(to_date('00:00:00', 'HH24:MI:SS') + (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME),  'HH24:MI:SS') AS Elapsed_Time,
	   MOD(TRUNC( 24 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Hours,
	   MOD(TRUNC( 24 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Minutes,
	   MOD(TRUNC( 24 * 60 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Seconds,
	   FT_PERFMON.START_DATE_TIME,
	   FT_PERFMON.END_DATE_TIME,
	   LOGONS.LOGONNO,
	   LOGONS.LOGONNAME,
	   LOGONS.USERNAME,
	   USERSESSNOLOG.COMPUTERNAME,
	   FRMNAME.FORMNO,
	   FRMNAME.FORMNAME,
	   FRMNAME.FORMTIT
  FROM FT_PERFMON
  	   INNER JOIN FT_PERFMON_KEYS ON (FT_PERFMON.FT_PERFMON_TYPENO = FT_PERFMON_KEYS.FT_PERFMON_TYPENO)
	   INNER JOIN USERSESSNOLOG ON (FT_PERFMON.PERFMONUSER = USERSESSNOLOG.USLRECNO)
	   INNER JOIN LOGONS ON (USERSESSNOLOG.LOGONNO = LOGONS.LOGONNO)
	   INNER JOIN PURORD ON (FT_PERFMON.TABLE_REF_VALUE = PURORD.PORNO)
	   LEFT OUTER JOIN FRMNAME ON (FT_PERFMON.FormNumber = FRMNAME.FORMNO)
 WHERE FT_PERFMON.FT_PERFMON_TYPENO = 5
   /*AND EXISTS(SELECT SESSNO.USERSESSRECNO
   	   			FROM USERSESSNOLOG SESSNO
			   WHERE SESSNO.ISLOGIN = 1
			   GROUP BY SESSNO.USERSESSRECNO
			  HAVING MAX(SESSNO.USLRECNO) = USERSESSNOLOG.USLRECNO)*/

UNION ALL

SELECT FT_PERFMON.PERFMON_BATCH_NO,
	   SALOFFNO.SALOFFNO AS PORSALOFF,
	   FT_PERFMON_KEYS.FT_PERFMON_TYPENO,
	   TRIM(FT_PERFMON_KEYS.FT_PERFMON_DESC) AS FT_PERFMON_DESC,
	   TRIM(FT_PERFMON.SELECTIONCRITERIA) AS SELECTIONCRITERIA,
	   TRIM(FT_PERFMON_KEYS.TABLE_REF) AS TABLE_REF,
	   SALOFFNO.SALOFFNO AS TABLE_REF_VALUE,
	   FT_PERFMON.NORECORDS,
	   NULL AS LitIteNo,
	   to_char(to_date('00:00:00', 'HH24:MI:SS') + (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME),  'HH24:MI:SS') AS Elapsed_Time,
	   MOD(TRUNC( 24 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Hours,
	   MOD(TRUNC( 24 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Minutes,
	   MOD(TRUNC( 24 * 60 * 60 * (FT_PERFMON.END_DATE_TIME - FT_PERFMON.START_DATE_TIME )), 60) Elapsed_Seconds,
	   FT_PERFMON.START_DATE_TIME,
	   FT_PERFMON.END_DATE_TIME,
	   LOGONS.LOGONNO,
	   LOGONS.LOGONNAME,
	   LOGONS.USERNAME,
	   USERSESSNOLOG.COMPUTERNAME,
	   FRMNAME.FORMNO,
	   FRMNAME.FORMNAME,
	   FRMNAME.FORMTIT
  FROM FT_PERFMON
  	   INNER JOIN FT_PERFMON_KEYS ON (FT_PERFMON.FT_PERFMON_TYPENO = FT_PERFMON_KEYS.FT_PERFMON_TYPENO)
	   INNER JOIN USERSESSNOLOG ON (FT_PERFMON.PERFMONUSER = USERSESSNOLOG.USLRECNO)
	   INNER JOIN LOGONS ON (USERSESSNOLOG.LOGONNO = LOGONS.LOGONNO)
	   INNER JOIN SALOFFNO ON (FT_PERFMON.TABLE_REF_VALUE = SALOFFNO.SALOFFNO)
	   LEFT OUTER JOIN FRMNAME ON (FT_PERFMON.FormNumber = FRMNAME.FORMNO)
 WHERE FT_PERFMON.FT_PERFMON_TYPENO >= 10
   /*AND EXISTS(SELECT SESSNO.USERSESSRECNO
   	   			FROM USERSESSNOLOG SESSNO
			   WHERE SESSNO.ISLOGIN = 1
			   GROUP BY SESSNO.USERSESSRECNO
			  HAVING MAX(SESSNO.USLRECNO) = USERSESSNOLOG.USLRECNO)*/
;
 
COMMENT ON TABLE FT_V_PERFMON IS 'v1.0.2 - View to give PerfMon Details';
