--########################################################################################################
-- View for PALAUDITS    
--########################################################################################################

CREATE OR REPLACE VIEW FT_V_PALAUDIT 
( PALAUDRECNO, PALLOCRECNO, PALLETNO, PALAUDBY, 
   AUDDATE, AUDTIME, TYP,  PALAUDDESCR,
   PALAUDFROMDESCR, AUDFROM, PALAUDTODESCR, AUDTO,  PALAUDTRANIND, 
   FORMNO, FORMNAME) 
AS 

SELECT PALAUDRECNO, PALAUDPALLOCRECNO, PALNOLOC.PALLETNO, trim(PALAUDBY), 
   PALAUDDATE, PALAUDTIME, PALAUDIT.PALAUDTYP,  PALAUDDESCR,
   PALAUDFROMDESCR, trim(PALAUDFROM), PALAUDTODESCR, trim(PALAUDTO), PALAUDTRANIND, 
   PALAUDIT.FORMNO, NVL(PALAUDIT.FORMNAME, FRMNAME.FORMNAME) FORMNAME
FROM PALAUDIT, PALAUDTYPES, FRMNAME, PALNOLOC
WHERE PALAUDIT.PALAUDTYP = PALAUDTYPES.PALAUDTYP(+)
AND PALAUDIT.FORMNO = FRMNAME.FORMNO(+)
AND PALAUDIT.PALAUDPALLOCRECNO = PALNOLOC.PALLOCRECNO 
ORDER BY PALAUDRECNO;



COMMENT ON TABLE FT_V_PALAUDIT IS '1.0.0';